<a href="https://colab.research.google.com/github/KIM-Jaegyeong/SBA2019_SeoulIT/blob/master/19_09_30Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install tensorflow

In [0]:
import tensorflow as tf


In [0]:
print(tf.__version__)


1.14.0


In [0]:
hello = tf.constant("Hello, Tensorflow")
print(hello)
print(type(hello))

# 텐서 자료형 : shape(), string / tf.constant() : Creates a constant tensor.


Tensor("Const_1:0", shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:
num1 = tf.constant(10)
num2 = tf.constant(20)
num3 = tf.add(num1, num2)
print(num3)

Tensor("Add:0", shape=(), dtype=int32)


In [0]:
# 2행 3열의 텐서를 생성
tensor = tf.constant(-1.0 , shape=[2,3])

In [0]:
## 그래프 실행하기 위하여
sess = tf.Session()
print(sess.run(hello))

b'Hello, Tensorflow'


In [0]:
print(sess.run(tensor))

[[-1. -1. -1.]
 [-1. -1. -1.]]


# 텐서 플로워의 자료형
- 플레이스 홀더 : 나중에 값을 입력받기 위한 사용되는 매개변수(parameter)
- shape(?,3)은 두번째 차원 요소가 3이고, 앞의 차원은 나중에 지정.

In [0]:
tensorX = tf.placeholder(tf.float32, [None, 2])
print(type(tensorX))
print(tensorX)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Placeholder:0", shape=(?, 2), dtype=float32)


In [0]:
# X에 넣을 데이터 초기화
x_data = [[1,1], [2,2]]


In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(tensorX, feed_dict={tensorX:x_data}))
sess.close()

[[1. 1.]
 [2. 2.]]


**행렬 연산**
- Y = X (2행2열) W(2행2열) + b(2행)

tf.random_normal : 정규 분포로부터 랜덤한 값 생성


In [0]:
tf.random_normal([3,2])

<tf.Tensor 'random_normal:0' shape=(3, 2) dtype=float32>

In [0]:
# None은 크기가 정해져 있지 않음을 의미
tensorX = tf.placeholder(tf.float32, [None, 2])

W = tf.Variable(tf.random_normal([2,2]))
b = tf.Variable(tf.random_normal([2,1]))
print(W)
print(b)

<tf.Variable 'Variable_4:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'Variable_5:0' shape=(2, 1) dtype=float32_ref>


In [0]:
# 직접 식 만들어보기
y = tf.matmul(tensorX, W) + b
y

<tf.Tensor 'add_5:0' shape=(2, 2) dtype=float32>

In [0]:
### x_data, W,b,y 값 출력

In [0]:

sess = tf.Session()
sess.run(tf.global_variables_initializer())
x_data = [[1,1], [2,2]]
print("x_data ==")
print(x_data)
print("W ==")
print(sess.run(W))
print("B ==")
print(sess.run(b))
print("y ==")
print(sess.run(y, feed_dict={tensorX:x_data}))

x_data ==
[[1, 1], [2, 2]]
W ==
[[-0.10528556 -0.9572519 ]
 [-0.33973247 -0.1350168 ]]
B ==
[[-0.55879295]
 [ 0.04813394]]
y ==
[[-1.003811   -1.6510617 ]
 [-0.84190214 -2.1364036 ]]


# 텐서 플로워

In [0]:
import tensorflow as tf

In [0]:
mnist = tf.keras.datasets.mnist
print(mnist)

<module 'tensorflow.python.keras.api._v1.keras.datasets.mnist' from '/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/api/_v1/keras/datasets/mnist/__init__.py'>


In [0]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [0]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
print(y_train[0:1])
X_train[0:1]

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
[5]


array([[[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           3,  18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,
           0,   0,   0

In [0]:
# 값의 정규화
# Dropout, 값의 정규화(0~!)
X_train, X_test = X_train/255.0, X_test/255.0

**tf 신경망 모델 만들기**

In [0]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(512, activation = tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [0]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [0]:
%%time
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 8s 131us/sample - loss: 0.2208 - acc: 0.9340
Epoch 2/5
60000/60000 [==============================] - 7s 123us/sample - loss: 0.0980 - acc: 0.9705
Epoch 3/5
60000/60000 [==============================] - 7s 122us/sample - loss: 0.0710 - acc: 0.9780
Epoch 4/5
60000/60000 [==============================] - 7s 119us/sample - loss: 0.0539 - acc: 0.9826
Epoch 5/5
60000/60000 [==============================] - 7s 119us/sample - loss: 0.0433 - acc: 0.9855
CPU times: user 52.9 s, sys: 2.43 s, total: 55.3 s
Wall time: 37.2 s


In [0]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 1s 53us/sample - loss: 0.0655 - acc: 0.9795


[0.0655316638088436, 0.9795]